# Generated by Django 6.0.4 on 2026-04-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Если установить дату и время в будущем — можно делать отложенные публикации.",
                null=True,
                verbose_name="Дата и время публикации",
            ),
        ),
    ]
